"""Generate the SIMULATED datasets the app ships with.

Real experimental waves are lab data and are not distributed. These stand in for
them. They are generated from a seeded PRNG and match no animal, no experiment
and no real measurement — but their *scales* are taken from the published
literature rather than invented, because a demo dataset on the wrong time scale
teaches the wrong thing about the detector's settings.

Two secretion models, because the two hormones do not behave alike:

  portal_fractions()  Hypophyseal-portal GnRH. Collected as continuous
                      fractions, so a "sample" is the GnRH accumulated over the
                      whole collection window, reported in pg/min. Secretion
                      itself is close to a square wave — Moenter et al. 1992
                      measured it at 30-s resolution: a rise of up to 50-fold
                      within 1 min, ~5.5 min sustained, back to baseline within
                      3 min, peaking near 24 pg/min (range 2-66) over an
                      interpulse baseline of 0.2-0.5 pg/min. Native GnRH is
                      cleared with a half-life of roughly 2-4 min, far shorter
                      than any practical collection window.

                      So there is NO decay tail to model. A burst falls almost
                      entirely inside one fraction, and appears as a one- or
                      two-sample spike with an abrupt return to baseline — two
                      samples only when the burst straddles a fraction boundary.
                      Modelling GnRH with an exponential clearance tail across
                      several samples is an artefact of the model, not a
                      property of the hormone.

  pulsatile()         Peripheral LH. Here exponential clearance IS right: LH is
                      sampled from jugular blood as a concentration, and its
                      half-life (tens of minutes in the ewe) is long compared
                      with a 10-min sampling interval, so each secretory event
                      leaves a decaying tail spanning several samples. This is
                      why portal GnRH and jugular LH traces look so unalike.

References for the scales used:
  Webster JR, Moenter SM, Barrell GK, Lehman MN, Karsch FJ. Role of the thyroid
    gland in seasonal reproduction. III. Thyroidectomy blocks seasonal
    suppression of gonadotropin-releasing hormone secretion in sheep.
    Endocrinology 1991;129(3):1635-43. PMID 1874193. THE PROTOCOL THE GnRH
    DATASETS BELOW ARE BUILT TO. Hypophyseal-portal blood from conscious
    ovariectomized, estradiol-implanted ewes, collected every 5 min for 6 h by
    an automated remote sampling system. GnRH reported as rate of collection in
    pg/min, not concentration. Thyroidectomized ewes that failed to enter
    anestrus: 11.2 +/- 1.4 pulses/6 h, and as many as 21 in one ewe.
    Thyroid-intact anestrous controls: generally no pulses at all. Figures 3-4
    put GnRH on a 0-2 pg/min axis over a baseline near 0.1-0.2, and LH on
    0-20 ng/ml. ONLY those axis ranges are taken from the figures; no data
    point is digitised from them. Pulses in that paper were identified with
    this very algorithm, at settings it prints: peak and nadir clusters of one
    point, t = 3.2/3.2 for GnRH and 2.32/2.32 for LH, stated to give false
    positive rates of 1% and 5% respectively. Reproducing those counts needs
    the original Fortran implementation, not the Igor one — see
    docs/validation-status.md on scale invariance, and note that a 1991 paper
    predates the Igor package anyway.
  Moenter SM, Brand RM, Midgley AR, Karsch FJ. Dynamics of gonadotropin-
    releasing hormone release during a pulse. Endocrinology 1992;130(1):503-10.
    PMID 1727719. (GnRH pulse waveform: square contour, ~5.5 min sustained.
    Its much larger pg/min figures are not in conflict with the 0-2 above —
    that study collected 30-s fractions, so it resolves the inside of a burst
    where this one averages over it.)
  Clarke IJ, Cummins JT. Endocrinology 1985;116(6):2376-83. PMID 3888609.
    (Ovine portal GnRH interpulse intervals, 27-53 min.)

Deterministic: rerunning reproduces the files byte for byte.

    python3 tools/make_synthetic.py
"""

import math
import random
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "synthetic"

BANNER = (
    "# SIMULATED DATA - not real experimental measurements.\n"
    "# Generated by tools/make_synthetic.py with a fixed seed. Matches no animal\n"
    "# and no experiment; the scales are drawn from the literature cited in that\n"
    "# script and in data/synthetic/README.md.\n"
    "# {kind}\n"
    "# Sampling interval: {dt:g} min.\n"
)


def _onsets(rng, span, mean_ipi):
    """Pulse onset times over [0, span), spaced irregularly around mean_ipi."""
    onsets, t = [], rng.uniform(0.3, 1.0) * mean_ipi
    while t < span:
        onsets.append(t)
        t += mean_ipi * rng.uniform(0.55, 1.55)
    return onsets


def _amplitudes(rng, n, lo, hi):
    """Log-uniform amplitudes: pulse size is skewed, not normal."""
    return [math.exp(rng.uniform(math.log(lo), math.log(hi))) for _ in range(n)]


def portal_fractions(
    seed, n, dt, baseline, amp_lo, amp_hi, mean_ipi, burst_min, cv, floor=0.01
):
    """GnRH in portal blood, collected as fractions of `dt` minutes.

    Each sample is the mean secretion rate over its collection window, so a
    square secretory burst of `burst_min` minutes contributes to a window in
    proportion to their overlap. No clearance term: see the module docstring.
    """
    rng = random.Random(seed)
    span = n * dt
    onsets = _onsets(rng, span, mean_ipi)
    amps = _amplitudes(rng, len(onsets), amp_lo, amp_hi)
    # Burst duration varies a little around the measured 5.5 min mean.
    bursts = [burst_min * rng.uniform(0.75, 1.3) for _ in onsets]

    rows = []
    for i in range(n):
        lo, hi = i * dt, (i + 1) * dt          # this fraction's collection window
        v = baseline
        for onset, a, dur in zip(onsets, amps, bursts):
            overlap = min(hi, onset + dur) - max(lo, onset)
            if overlap > 0:
                v += a * overlap / dt          # time-average over the window
        v *= 1.0 + rng.gauss(0.0, cv)          # assay noise
        v = max(v, floor)
        rows.append((hi, v, max(v * cv, floor)))
    return rows


def pulsatile(seed, n, dt, baseline, half_life, amp_lo, amp_hi, mean_ipi, cv, floor=0.05):
    """Peripheral LH: baseline plus secretory pulses with exponential clearance.

    half_life, mean_ipi and dt are all in minutes.
    """
    rng = random.Random(seed)
    span = n * dt
    onsets = _onsets(rng, span, mean_ipi)
    amps = _amplitudes(rng, len(onsets), amp_lo, amp_hi)
    k = math.log(2) / half_life

    rows = []
    for i in range(n):
        t = (i + 1) * dt
        v = baseline
        for onset, a in zip(onsets, amps):
            d = t - onset
            if d >= 0:
                v += a * math.exp(-k * d)      # fast rise, then clearance
        v *= 1.0 + rng.gauss(0.0, cv)
        v = max(v, floor)
        rows.append((t, v, max(v * cv, floor)))
    return rows


def write(name, kind, dt, rows, cols=3, prec=3):
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / name
    with path.open("w") as f:
        f.write(BANNER.format(kind=kind, dt=dt))
        if cols == 3:
            f.write("time,value,error\n")
            for t, v, e in rows:
                f.write(f"{t:g},{v:.{prec}f},{e:.{prec}f}\n")
        elif cols == 2:
            f.write("time,value\n")
            for t, v, _ in rows:
                f.write(f"{t:g},{v:.{prec}f}\n")
        else:
            f.write("value\n")
            for _, v, _ in rows:
                f.write(f"{v:.{prec}f}\n")
    print(f"{path.relative_to(OUT.parent.parent)}: {len(rows)} points, dt={dt} min")


# --- Portal GnRH, thyroidectomized ewe: Webster 1991's main finding ----------
# The paper's protocol exactly: 5-min fractions for 6 h, so 72 samples. 11
# pulses over the 6 h is the reported mean (11.2 +/- 1.4). Amplitudes are set so
# peak samples land between about 0.6 and 2 pg/min, which is the axis range its
# Figs. 3-4 are drawn on, over a baseline hugging 0.1-0.2. Only the axis scale
# is taken from the figure; no data point is read off it.
write(
    "sim_gnrh_thx_ewe.csv",
    "Resembles portal GnRH in a thyroidectomized ewe: 5-min fractions, 6 h (pg/min).",
    5,
    portal_fractions(
        seed=101, n=72, dt=5, baseline=0.16,
        amp_lo=0.8, amp_hi=2.8, mean_ipi=32.0, burst_min=5.5, cv=0.078,
    ),
)

# --- The fastest ewe in that study: 21 pulses in the same 6 h ----------------
# Not an invented hard case — an observed one (Fig. 4A, and that panel reaches
# the same ~2 pg/min ceiling). At an interpulse interval near 17 min, a 5-min
# fraction leaves about three samples per cycle, which is where the peak and
# nadir windows begin to overlap neighbouring pulses and adjacent pulses merge.
# It is here to make that limit visible.
write(
    "sim_gnrh_thx_fast.csv",
    "Resembles the highest-frequency ewe in that study: 21 pulses in 6 h (pg/min).",
    5,
    portal_fractions(
        seed=131, n=72, dt=5, baseline=0.18,
        amp_lo=0.7, amp_hi=2.6, mean_ipi=17.0, burst_min=5.5, cv=0.078,
    ),
)

# --- Thyroid-intact anestrous control: the paper's own negative control ------
# "In 4 of 5 thyroid-intact ewes, there were no pulses of either LH or GnRH."
# A negative control drawn from the same protocol as the positive one is worth
# more than a generic flat line: everything but the pulses is the same.
write(
    "sim_gnrh_intact.csv",
    "Resembles a thyroid-intact anestrous ewe: same protocol, no GnRH pulses (pg/min).",
    5,
    portal_fractions(
        seed=161, n=72, dt=5, baseline=0.16,
        amp_lo=0.001, amp_hi=0.002, mean_ipi=1e9, burst_min=5.5, cv=0.078,
    ),
)

# --- Peripheral LH, 10-min sampling over 12 h -------------------------------
write(
    "sim_lh.csv",
    "Resembles peripheral (jugular) LH sampled every 10 min (ng/ml).",
    10,
    pulsatile(
        seed=202, n=73, dt=10, baseline=4.0, half_life=25.0,
        amp_lo=2.0, amp_hi=9.0, mean_ipi=70.0, cv=0.07,
    ),
)

# --- Peripheral LH, a 24-h run at lower pulse frequency ----------------------
write(
    "sim_lh_long.csv",
    "Resembles a 24-h peripheral LH time course, 10-min sampling (ng/ml).",
    10,
    pulsatile(
        seed=303, n=145, dt=10, baseline=4.5, half_life=25.0,
        amp_lo=2.5, amp_hi=9.5, mean_ipi=190.0, cv=0.075,
    ),
)

# --- Value-only series, for files that carry no time column ------------------
write(
    "sim_values_only.csv",
    "Resembles peripheral LH with no time column; supply the interval yourself.",
    10,
    pulsatile(
        seed=404, n=80, dt=10, baseline=3.5, half_life=25.0,
        amp_lo=2.0, amp_hi=8.0, mean_ipi=80.0, cv=0.08,
    ),
    cols=1,
)

# --- A flat, pulse-free control: checks the false-positive rate --------------
write(
    "sim_flat_control.csv",
    "Resembles a pulse-free negative control at the LH baseline (ng/ml).",
    10,
    pulsatile(
        seed=505, n=72, dt=10, baseline=4.0, half_life=25.0,
        amp_lo=0.001, amp_hi=0.002, mean_ipi=1e9, cv=0.07,
    ),
)
