"""Generate the SIMULATED datasets the app ships with.

The real experimental waves are lab data and are not distributed. These stand
in for them: same character (sampling rate, baseline level, pulse amplitude
range, assay CV) so the app demonstrates realistically, but generated from a
seeded PRNG and matching no animal, no experiment, and no real measurement.

Deterministic: rerunning reproduces the files byte for byte.

    python3 tools/make_synthetic.py
"""

import math
import random
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "synthetic"

BANNER = (
    "# SIMULATED DATA — not real experimental measurements.\n"
    "# Generated by tools/make_synthetic.py with a fixed seed.\n"
    "# Resembles {kind} in sampling rate, baseline and pulse amplitude only.\n"
)


def pulsatile(
    seed, n, dt, baseline, half_life, amp_lo, amp_hi, mean_ipi, cv, floor=0.0
):
    """A baseline plus exponentially-decaying secretory pulses, with assay noise.

    half_life, mean_ipi and dt are all in the same time unit.
    """
    rng = random.Random(seed)

    # pulse onsets: gamma-ish spacing around mean_ipi, never two in a row
    onsets, t = [], rng.uniform(0.4, 1.0) * mean_ipi
    while t < n * dt:
        onsets.append(t)
        t += mean_ipi * rng.uniform(0.55, 1.55)
    amps = [math.exp(rng.uniform(math.log(amp_lo), math.log(amp_hi))) for _ in onsets]

    k = math.log(2) / half_life
    rows = []
    for i in range(n):
        tt = (i + 1) * dt
        v = baseline
        for onset, a in zip(onsets, amps):
            d = tt - onset
            if d >= 0:
                # fast rise (one sample) then exponential clearance
                v += a * math.exp(-k * d)
        v *= 1.0 + rng.gauss(0.0, cv)       # multiplicative assay noise
        v = max(v, floor)
        err = max(v * cv, floor if floor else 0.01)
        rows.append((tt, v, err))
    return rows


def write(name, kind, rows, cols=3, prec=3):
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / name
    with path.open("w") as f:
        f.write(BANNER.format(kind=kind))
        if cols == 3:
            f.write("time,value,error\n")
            for t, v, e in rows:
                f.write(f"{t:g},{v:.{prec}f},{e:.{prec}f}\n")
        elif cols == 2:
            f.write("time,value\n")
            for t, v, _ in rows:
                f.write(f"{t:g},{v:.{prec}f}\n")
        else:
            f.write("value\n")
            for _, v, _ in rows:
                f.write(f"{v:.{prec}f}\n")
    print(f"{path.relative_to(OUT.parent.parent)}: {len(rows)} points")


# --- GnRH-like: fast sampling, near-zero baseline, tall sharp pulses ---------
write(
    "sim_gnrh.csv",
    "GnRH portal sampling",
    pulsatile(
        seed=101, n=96, dt=1, baseline=0.35, half_life=1.1,
        amp_lo=4.0, amp_hi=26.0, mean_ipi=5.2, cv=0.07, floor=0.01,
    ),
    prec=3,
)

# --- LH-like: slower sampling, substantial baseline, modest pulses ----------
write(
    "sim_lh.csv",
    "peripheral LH sampling",
    pulsatile(
        seed=202, n=61, dt=1, baseline=5.5, half_life=3.2,
        amp_lo=2.5, amp_hi=11.0, mean_ipi=11.0, cv=0.065, floor=0.05,
    ),
    prec=3,
)

# --- long 10-minute-sampling series, the "set1" shape ------------------------
write(
    "sim_lh_long.csv",
    "a long LH time course at 10-minute sampling",
    pulsatile(
        seed=303, n=145, dt=10, baseline=6.0, half_life=34.0,
        amp_lo=3.0, amp_hi=16.0, mean_ipi=190.0, cv=0.08, floor=0.05,
    ),
    prec=3,
)

# --- value-only series, standing in for the manual test waves ---------------
write(
    "sim_values_only.csv",
    "a value-only series with no time column",
    pulsatile(
        seed=404, n=80, dt=1, baseline=1.2, half_life=1.6,
        amp_lo=2.0, amp_hi=9.0, mean_ipi=7.0, cv=0.09, floor=0.01,
    ),
    cols=1,
    prec=3,
)

# --- a flat, pulse-free control: useful for checking false positives --------
write(
    "sim_flat_control.csv",
    "a flat negative control with no pulses",
    pulsatile(
        seed=505, n=72, dt=1, baseline=2.0, half_life=1.0,
        amp_lo=0.001, amp_hi=0.002, mean_ipi=1e9, cv=0.07, floor=0.01,
    ),
    prec=3,
)
