// About page: provenance, how the algorithm works, honest caveats, and
// pointers to the literature. Every citation below was verified against
// PubMed/DOI at the time of writing — do not add one you have not checked.

import { BORN, BUILT, VERSION, longDate } from "./version";
import { ContactForm } from "./Contact";
import { downloadText } from "./chart/export";
import { TEMPLATE_CSV, TEMPLATE_NAME } from "./template";

export function About({ onBack }: { onBack: () => void }) {
  return (
    <div className="about">
      <button onClick={onBack}>← Back to the app</button>

      <h1>About no_peak</h1>
      <p className="cite">
        Version {VERSION} · built {longDate(BUILT)} · born {longDate(BORN)}
      </p>
      <p className="lede">
        no_peak is a browser-based implementation of <strong>CLUSTER</strong>, the pulse-detection
        algorithm for endocrine time-series data developed by Johannes D. Veldhuis and Michael L.
        Johnson. It is a faithful port of the Igor Pro implementation used in the Moenter Lab, with
        the original Fortran available as a switchable mode.
      </p>
      <p>
        Your data runs entirely on your machine. There is no analytics, and no code path that
        uploads a loaded recording — it never leaves the browser tab. The one exception on this
        page is the contact form at the bottom, which sends only what you type into it.
      </p>

      <h2 id="prepare">Preparing a file to upload</h2>
      <p>
        The quickest way to see the expected shape is to open the example:{" "}
        <button className="linkish" onClick={() => downloadText(TEMPLATE_CSV, TEMPLATE_NAME)}>
          download a sample CSV
        </button>
        . Every dataset in the <strong>Sample data</strong> menu is a file in the same format, so
        loading one and exporting the results is another way to see it.
      </p>
      <h3 id="twokinds">Two kinds of bundled data, and why both</h3>
      <p>
        The <strong>Sample data</strong> menu holds two things that must not be mistaken for one
        another. They are labeled distinctly everywhere they appear, and the distinction is not
        cosmetic — they answer different questions.
      </p>
      <ul>
        <li>
          <strong>Real animals.</strong> Eight records read off the published figures of Webster et
          al. (1991) with an author&apos;s permission — four ewes, portal GnRH during collection and
          jugular LH from a fortnight earlier. These are measurements from actual sheep. What they
          carry is the pulse call <em>that paper&apos;s own CLUSTER run made</em>, marked on the
          printed trace. That is a published answer, but an answer about what a detector
          reported, not about what the animal secreted. They are approximate to the width
          of a printed line, and their <strong>error column is reconstructed, not
          digitized</strong> — the figures print no error bars and the paper does not report what
          per-sample error it gave CLUSTER, so each file supplies <code>max(floor, 8% of value)</code>.
          For LH that floor is the assay sensitivity the paper reports; for GnRH it was fitted to
          that paper&apos;s own pulse calls. Detection needs it: at one-point windows every
          estimated error model computes the error from a window containing the pulse, so a clean
          tall pulse inflates its own error and hides itself.
        </li>
        <li>
          <strong>Simulated models.</strong> Generated by <code>tools/make_synthetic.py</code> from
          a fixed seed. They correspond to no animal. What they carry is the opposite kind of truth:
          every pulse in them was put there deliberately, so you know exactly where the pulses are
          and can measure what a detector misses and invents. No real record can tell you that.
        </li>
      </ul>
      <p className="note">
        <strong>One overlap to be aware of.</strong> The simulated GnRH records were built to the
        protocol of the very same paper the real ones come from — 5-min portal fractions over 6 h,
        the same concentration scale, pulse intervals near the ones it reports. That was done before
        the paper&apos;s data was available. They are a <em>model of that protocol</em>, not a
        version of those animals: no simulated record corresponds to ewe #8067 or any other. Their
        generating parameters — baseline, amplitude range, burst duration, pulse interval, assay
        noise, and the seed — are stated on each dataset and in{" "}
        <code>data/synthetic/README.md</code>.
      </p>
      <p>
        The scales of the simulated data are taken from the published literature rather than chosen
        to look right, because a demo dataset on the wrong time scale teaches the wrong window
        widths. The two hormones are generated by different models on purpose: portal GnRH is
        collected as integrated fractions and cleared far faster than a collection window, so its
        pulses are square bursts landing in one or two samples with no decay tail, while peripheral
        LH has a half-life long against the sampling interval and does decay over several samples.
        That is why the two look so unalike.
      </p>

      <h3>Igor files</h3>
      <p>
        Igor packed experiments (<code>.pxp</code>) and binary waves (<code>.ibw</code>) load
        directly — no export to text first. The app lists the numeric waves in the file and you
        choose which to analyze, along with its error and time waves if it has them. Where the
        Igor Cluster package&apos;s column naming is used (<code>…C1(RD)</code> for data,{" "}
        <code>C2(STDEV)</code> for errors, <code>C3(Times)</code> for the time base) the pairing is
        proposed automatically, and you can override it. A wave&apos;s own x scaling becomes the
        sampling interval and its x units set the time axis, so the figure is labeled from the
        data rather than from memory. Both byte orders are read, including experiments written on
        older Macs.
      </p>
      <p>
        Ticking <strong>several waves at once</strong> analyzes them as separate records under one
        set of detection settings — see <a href="#concatenate">analyzing a whole study</a> below.
      </p>

      <h3>Text files</h3>
      <p>
        A file is plain text with one sample per line. Commas, tabs, semicolons, or spaces all
        work, and a header row is optional — it is detected and skipped automatically. Three
        layouts are accepted:
      </p>
      <ul>
        <li>
          <strong>One column — <code>value</code>.</strong> Just concentrations, in order. Times
          are generated from the <em>Sampling interval</em> field, which appears in the settings
          when a file has no time column.
          <span className="cite">0.42 ⏎ 0.38 ⏎ 0.45 ⏎ …</span>
        </li>
        <li>
          <strong>Two columns — <code>time,value</code>.</strong> Use this when you have real
          sample times. Times should be evenly spaced: the algorithm compares fixed-width windows
          of <em>points</em>, and widths and areas are computed from the first interval.
          <span className="cite">10,0.42 ⏎ 20,0.38 ⏎ 30,0.45 ⏎ …</span>
        </li>
        <li>
          <strong>Three columns — <code>time,value,error</code>.</strong> The best option if your
          assay reports per-sample precision. The third column is the measurement error (SD or SEM)
          for that sample, and selecting the &quot;Error Wave&quot; model uses it directly instead
          of estimating error from the data.
          <span className="cite">10,0.42,0.03 ⏎ 20,0.38,0.03 ⏎ …</span>
        </li>
      </ul>
      <p>
        You can also select <strong>two files at once</strong> — a data file and a separate error
        file — and they will be paired, provided they have the same number of rows. The error file
        is recognized by its name containing <code>err</code>, <code>sd</code>, <code>sem</code>,
        or <code>stdev</code>. Either way, the app asks before switching to your errors, because
        scaling the test by measurement error changes which pulses are detected.
      </p>

      <h2 id="concatenate">Analyzing a whole study at once</h2>
      <p>
        A common working practice: rather than tune the detector separately for each animal — which
        makes the settings, and therefore the pulse counts, incomparable between animals — you
        concatenate every record into one long trace, run it once, and chop the output back apart
        by animal afterwards.
      </p>
      <p>
        The instinct is right and the chopping is unnecessary. Select several files at once, or
        tick several waves in an Igor file, and each is treated as its own record: identical
        settings across all of them, results reported per record and pooled, and one figure with
        every record on the same axis and the joins marked.
      </p>
      <p>
        Doing it this way also avoids two things that go wrong when the trace is genuinely
        concatenated first. The join between two animals is a step change the detector has no way
        to know is artificial, so it reads as a pulse edge — inventing a pulse there, or swallowing
        a real one at the record&apos;s edge. And a pooled interpulse interval computed across the
        join is a measurement of nothing. Here every detection window stays inside one record, so
        neither can happen, and the <strong>Per-record CSV</strong> export gives you one row per
        animal ready to paste into a statistics package.
      </p>
      <h3 id="batch">When there are too many to click through</h3>
      <p>
        Selecting files stops scaling somewhere around fifty records. The same algorithm runs from
        a command line, over a whole directory, writing exactly the per-record table described
        above — so a study is one command rather than an afternoon of uploads. It is the same
        code, not a reimplementation: the batch tool calls the function behind the{" "}
        <strong>Per-record CSV</strong> button, and the test suite checks the two against each
        other on records with published pulse counts.
      </p>
      <p>
        <a className="btnlink" href="/methods#batch">
          How to run it in batch →
        </a>
      </p>
      <h3>Things that will trip you up</h3>
      <ul>
        <li>
          <strong>Every row must be numeric.</strong> There is no support for blanks, gaps, or
          missing-value markers like <code>NA</code>, <code>ND</code>, or <code>-</code>; loading
          stops with the offending line number. Interpolate or trim before uploading, and say which
          you did in your methods.
        </li>
        <li>
          <strong>Rows must all have the same number of columns.</strong> A stray trailing comma on
          one line is the usual culprit.
        </li>
        <li>
          <strong>Export as CSV, not .xlsx.</strong> From Excel: File ▸ Save As ▸ CSV. From Igor
          there is no need to export at all — load the <code>.pxp</code> directly.
        </li>
        <li>
          <strong>Decimal commas are not supported.</strong> In locales that write
          <code>0,42</code>, the comma is read as a column separator. Save with a period.
        </li>
        <li>
          <strong>Errors of zero break the t-test</strong> — a zero-error sample makes the pooled
          variance vanish. If your assay reports zeros, use one of the estimated error models
          instead.
        </li>
        <li>
          Lines starting with <code>#</code> or <code>//</code> are ignored, so you can keep notes
          at the top of the file.
        </li>
      </ul>

      <h2>How CLUSTER works</h2>
      <p>
        CLUSTER asks one local question, repeatedly. At every sample it compares the mean of the
        next <em>n</em>
        <sub>peak</sub> points against the mean of the preceding <em>n</em>
        <sub>nadir</sub> points using a pooled t-test, scaled by the measurement error at each
        point. When that t-statistic exceeds the user&apos;s threshold, the sample is flagged as a
        significant increase (an <em>up</em>) or, scanning for the opposite sign, a significant
        decrease (a <em>down</em>). A second pass assembles those flags into pulse regions, and a
        third tabulates the resulting peaks and valleys.
      </p>
      <p>
        What makes this approach durable is what it does <em>not</em> assume. There is no pulse
        shape, no secretion-and-clearance kinetic model, no baseline function, and no assumption
        that pulses are regularly spaced. The only model is the measurement error: because the test
        is scaled by each point&apos;s error, a large jump in a noisy stretch of the record may not
        register, while a modest, well-measured rise can. That is deliberate — it keeps the
        detector honest about assay precision rather than about biology.
      </p>
      <p>
        The price of that simplicity is that the detection parameters — the two window widths, the
        two t-score thresholds, and the minimum value a pulse must reach — <em>are</em> the model.
        Different settings give different answers, so publications using CLUSTER should report all
        five along with the error model,
        and it is worth checking that your conclusions survive a sweep of nearby values. CLUSTER
        also identifies <em>when</em> pulses occur; it does not estimate secretion rates, hormone
        half-life, or pulse mass. Those are the province of deconvolution methods, several of which
        are linked below.
      </p>
      <p>
        CLUSTER is forty years old, and newer methods do detect more pulses. In the validation of
        AutoDecon on synthetic LH data, AutoDecon reached about 96% sensitivity against
        CLUSTER&apos;s 80% — but CLUSTER produced markedly fewer false positives, roughly 1%
        against 6%. That trade is the honest summary of why the algorithm is still in use: it is
        conservative, its assumptions are few and inspectable, and it fails in predictable ways.
        One caveat on that 1%, from testing this port against simulated data with known answers:
        it holds for records packed with pulses, which is what those benchmarks used. On sparser
        records the same code produces materially more false positives, so treat the figure as a
        property of the benchmark as much as of the algorithm.
        Whether that is the right trade depends on whether missing a pulse or inventing one is
        worse for your question.
      </p>

      <h3 id="presets">Published settings</h3>
      <p>
        Because the five detection parameters <em>are</em> the model, a published analysis can only
        be reproduced if the paper reported them. Where one did, its settings are a click away in{" "}
        <strong>Start from published settings</strong>, with the citation attached — both to
        reproduce that analysis and as a defensible starting point for the same hormone and
        protocol.
      </p>
      <p>
        Webster et al. (1991), measuring GnRH in hypophyseal-portal blood of the ewe every 5 minutes
        for 6 hours, used peak and nadir clusters of a single point with t = 3.2 for GnRH and
        t = 2.32 for jugular LH, reporting false positive rates of 1% and 5% respectively. Those are
        the two presets currently shipped. The simulated portal GnRH datasets are built to that
        paper&apos;s protocol, and at its settings the simulated record built to that
        protocol returns the 11 pulses per 6 hours it reports.
        <span className="cite">
          Webster JR, Moenter SM, Barrell GK, Lehman MN, Karsch FJ. Role of the thyroid gland in
          seasonal reproduction. III. Endocrinology 1991;129(3):1635–43.
        </span>
      </p>

      <h3 id="scale">A caveat: the Igor t-score depends on your units</h3>
      <p className="note">
        The two implementations differ in how they pool the per-point measurement error, and the
        difference is not cosmetic. The original Fortran sums the errors <em>squared</em> — a
        pooled variance, which carries the units of your data, so the t-statistic that divides by
        it is dimensionless. The Igor implementation sums them <em>unsquared</em>. Its pooled term
        therefore carries units of the square root of your data, and the resulting t-score is not
        dimensionless: multiply a record by a constant and every t-score moves by the square root
        of that constant.
      </p>
      <p>
        The practical consequence is that under the Igor implementation, the same record expressed
        in ng/ml and in pg/ml gives different pulse counts at the same threshold. On the bundled
        portal GnRH dataset, rescaling the data over four orders of magnitude — which cannot change
        anything about where its pulses are — moves the count from zero to more pulses than were
        generated. The original Fortran returns the same answer at every scale.
      </p>
      <p>
        How much it bites depends on the window widths, because the pooled term averages over
        <em>n</em><sub>peak</sub> + <em>n</em><sub>nadir</sub> points: the more points, the more the
        distortion washes out. At the two-point default windows it is usually mild. At one-point
        windows — which is what several published analyses specify — it is severe, and the app says
        so when you select them.
      </p>
      <p>
        This is preserved rather than corrected, because the Igor implementation is the validation
        oracle for this port and silently diverging from it would make the port untestable. If you
        are reproducing a published threshold, or your values are far from order 1, use the
        original Fortran implementation. If you are comparing groups within one study whose data
        is all on the same scale, the Igor behavior will not mislead you — but report which
        implementation you used.
      </p>

      <h3 id="terms">What the numbers are called</h3>
      <p>
        Two of the reported quantities get conflated constantly, including by the original
        program&apos;s own column headings, so this app names them apart:
      </p>
      <ul>
        <li>
          <strong>Peak value</strong> is the highest concentration reached inside the pulse, in the
          units of your data. It is an absolute level, and it depends on where the baseline
          happened to be. The Fortran printed this as <code>HEIGHT</code>.
        </li>
        <li>
          <strong>Baseline</strong>, shown as the nadir column, is the mean of the{" "}
          <em>n</em><sub>nadir</sub> points immediately before the pulse begins.
        </li>
        <li>
          <strong>Amplitude</strong> is the difference: peak value minus that baseline — the rise
          the pulse actually represents. The Fortran printed this as <code>L INCREASE</code>, which
          is where much of the confusion starts.
        </li>
      </ul>
      <p>
        Both are given per pulse and as a mean ± SD, because which one belongs in a result depends
        on the question. A treatment that raises basal secretion without changing pulse size moves
        peak value and leaves amplitude alone; one that changes pulse size does the reverse.
        Reporting only &quot;peak height&quot; without saying which you meant makes the two
        indistinguishable to a reader.
      </p>
      <p>
        <strong>Pulse frequency</strong> is counted over the whole record — pulses divided by
        elapsed time — and not as the reciprocal of the mean interpulse interval. The interval only
        spans the first pulse to the last and needs two pulses to exist at all, so on a record with
        long quiet stretches it reads high. Both are shown; the frequency is the one that means
        what a methods section means by it.
      </p>

      <h3 id="reporting">Report your error model, not just the five parameters</h3>
      <p>
        This used to be advice on principle. It is now a measurement. The app bundles eight real
        hormone records digitized, with an author&apos;s permission, from the figures of a 1991
        study that used this same algorithm — figures which mark every pulse that study&apos;s own
        analysis identified, 70 in all. That is an answer key, not ground truth about
        secretion — and because the study used this same algorithm, agreeing with it
        shows consistency between implementations rather than independent validation.
      </p>
      <p>
        That paper reports its window widths and both t-scores, which is more than most do. Given
        those settings <em>and</em> an assay-shaped measurement error, this port recovers
        67 of the 70 published pulses with one false positive — though two constants in
        that error model were fitted, and they buy the precision rather than the
        sensitivity. Given only the settings the
        paper prints, and estimating the error from the data as any reader would have to, the same
        records yield anywhere from no pulses at all to 171 detections — depending on nothing but
        which estimator is chosen.
      </p>
      <p>
        So a study can report every detection parameter it is conventionally asked for and still not
        be reproducible. If you publish a CLUSTER analysis, say which error model you used and,
        where the error came from your assay rather than from the data, deposit it.
      </p>

      <h3>Error models</h3>
      <p>
        The per-point error can be estimated from the spread of the data values themselves —
        over a sliding window, or across the whole record, as an SD or a standard error; from a square-root model for
        count-like data; from a fixed value; or from a user-supplied error column in your file
        (the &quot;Error Wave&quot; option), which is what you want when your assay reports its own
        per-sample precision.
      </p>

      <h2>Provenance of this port</h2>
      <p>
        Three implementations sit behind this app, and the differences between them are documented
        rather than smoothed over:
      </p>
      <ul>
        <li>
          <strong>CLUST5.MPF</strong> — the original Fortran 77 console program (version 6.01),
          built for VAX, PC, Macintosh, and Unix from a single source with preprocessor switches.
          It printed line-printer reports and drew its plots as columns of asterisks.
        </li>
        <li>
          <strong>do_cluster.mpf</strong> — a later Fortran 90 rewrite (&quot;CLUSTER8&quot;,
          version 8.00) wrapped in a Winteracter GUI, adding outlier detection, residual runs
          tests, and secretion summary statistics.
        </li>
        <li>
          <strong>ClusterMasterV4-1.ipf</strong> — the Igor Pro port, and the validation oracle for
          this project. Its numbers are the ones no_peak is tested against.
        </li>
      </ul>
      <p>
        The Igor port and the original Fortran genuinely disagree in a few places, so the{" "}
        <strong>Implementation</strong> selector switches between them rather than picking a
        winner. The pooled variance term differs (Igor sums the standard deviations, the Fortran
        squares them first), and the pulse-assembly pass marks a different number of points per
        up-flag. Selecting the Fortran mode also switches the interface to the green-phosphor
        terminal look the program originally ran under, which is either a useful signal that
        you&apos;ve left the validated path or simply a nice bit of history, depending on your
        mood.
      </p>
      <p>
        One deliberate departure from both: when a pulse is still in progress at the end of the
        record, the original code silently dropped it, because the statistics that need a
        following baseline cannot be computed. no_peak counts that pulse by default and marks the
        affected statistics as unavailable, since a detected pulse that vanishes from the table is
        more confusing than one with missing columns. The original behavior is one checkbox away.
      </p>

      <h2>Credit</h2>
      <p>
        CLUSTER is the work of <strong>Michael L. Johnson</strong> and{" "}
        <strong>Johannes D. Veldhuis</strong>. Johnson, a biophysicist and Professor Emeritus of
        Pharmacology at the University of Virginia, spent a career building the numerical methods
        and freely distributed software that much of the endocrine pulsatility literature rests on
        — CLUSTER, the deconvolution family, AutoDecon, and a long run of methodological writing on
        parameter estimation and confidence intervals in biological data, including his editorship
        of the <em>Numerical Computer Methods</em> volumes of{" "}
        <em>Methods in Enzymology</em>. There was never a separate software paper for CLUSTER; the
        program was distributed directly by the authors, and the field cites the 1986 paper below
        as the citation for the program itself. This port is made with Michael Johnson&apos;s
        approval, and exists because that software was shared openly and kept working for four
        decades. Any errors in the translation are ours, not theirs.
      </p>

      <h2>Key references</h2>
      <p className="note">
        Every citation on this page was checked against PubMed or publisher records. If you spot an
        error, please report it — a wrong citation in a tool other people cite is worth fixing
        quickly.
      </p>

      <h3>The algorithm</h3>
      <ul>
        <li>
          <a href="https://doi.org/10.1152/ajpendo.1986.250.4.E486" target="_blank" rel="noreferrer">
            Cluster analysis: a simple, versatile, and robust algorithm for endocrine pulse
            detection
          </a>{" "}
          — the original CLUSTER paper, and the correct citation to use for this software.
          <span className="cite">
            Veldhuis JD, Johnson ML. <em>Am J Physiol.</em> 1986 Apr;250(4 Pt 1):E486–93. PMID
            3008572.
          </span>
        </li>
        <li>
          <a href="https://doi.org/10.1203/00006450-198607000-00011" target="_blank" rel="noreferrer">
            Appraising endocrine pulse signals at low circulating hormone concentrations
          </a>{" "}
          — the regional coefficient-of-variation approach behind the error models.
          <span className="cite">
            Veldhuis JD, Weiss J, Mauras N, Rogol AD, Evans WS, Johnson ML.{" "}
            <em>Pediatr Res.</em> 1986 Jul;20(7):632–7. PMID 3725460.
          </span>
        </li>
        <li>
          <a href="https://doi.org/10.1210/endo-124-5-2541" target="_blank" rel="noreferrer">
            In vivo biological validation and biophysical modeling of the sensitivity and positive
            accuracy of endocrine peak detection. I. The LH pulse signal
          </a>{" "}
          — how well the detector actually recovers known pulses.
          <span className="cite">
            Urban RJ, Johnson ML, Veldhuis JD. <em>Endocrinology.</em> 1989 May;124(5):2541–7. PMID
            2707166.
          </span>
        </li>
        <li>
          <a href="https://doi.org/10.1016/S0076-6879(94)40056-3" target="_blank" rel="noreferrer">
            Testing pulse detection algorithms with simulations of episodically pulsatile
            substrate, metabolite, or hormone release
          </a>{" "}
          — the simulation methodology for characterizing false-positive and false-negative rates.
          <span className="cite">
            Veldhuis JD, Johnson ML. <em>Methods Enzymol.</em> 1994;240:377–414. PMID 7823840.
          </span>
        </li>
        <li>
          <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC2662597/" target="_blank" rel="noreferrer">
            Biomathematical modeling of pulsatile hormone secretion: a historical perspective
          </a>{" "}
          — the clearest account of where CLUSTER sits among pulse detectors, and a good starting
          point if you are choosing a method.
          <span className="cite">
            Evans WS, Farhy LS, Johnson ML. <em>Methods Enzymol.</em> 2009;454:345–66. PMID
            19216934.
          </span>
        </li>
      </ul>

      <h3>The Igor implementation, and work that used it</h3>
      <p>
        The Igor Pro port that no_peak is validated against was introduced in Vanacker et al.
        (2017), with Michael Johnson as a co-author; papers from the Moenter lab cite it as the
        software reference. The studies below give a sense of how the algorithm is used in
        practice, and the parameters they report are a reasonable starting point for similar data:
        cluster sizes of 2 points for both peak and nadir with t-scores of 2, which are also
        no_peak&apos;s defaults.
      </p>
      <ul>
        <li>
          <a href="https://doi.org/10.1210/en.2017-00382" target="_blank" rel="noreferrer">
            Long-term recordings of arcuate nucleus kisspeptin neurons reveal patterned activity
            that is modulated by gonadal steroids in male mice
          </a>{" "}
          — the source of the Igor implementation, verified against the native version.
          <span className="cite">
            Vanacker C, Moya MR, DeFazio RA, Johnson ML, Moenter SM. <em>Endocrinology.</em> 2017
            Oct;158(10):3553–64. PMID 28938398.
          </span>
        </li>
        <li>
          <a href="https://doi.org/10.7554/eLife.43999" target="_blank" rel="noreferrer">
            Genetic dissection of the different roles of hypothalamic kisspeptin neurons in
            regulating female reproduction
          </a>{" "}
          — LH pulse detection in serially sampled mice.
          <span className="cite">
            Wang L, Vanacker C, Burger LL, Barnes T, Shah YM, Myers MG, Moenter SM.{" "}
            <em>eLife.</em> 2019;8:e43999. PMID 30946012.
          </span>
        </li>
        <li>
          <a href="https://doi.org/10.1523/JNEUROSCI.2428-17.2017" target="_blank" rel="noreferrer">
            Glutamatergic transmission to hypothalamic kisspeptin neurons is differentially
            regulated by estradiol through estrogen receptor α in adult female mice
          </a>
          <span className="cite">
            Wang L, Burger LL, Greenwald-Yarnell ML, Myers MG Jr, Moenter SM. <em>J Neurosci.</em>{" "}
            2018 Jan 31;38(5):1061–72. PMID 29114074.
          </span>
        </li>
        <li>
          <a href="https://doi.org/10.1523/ENEURO.0223-20.2020" target="_blank" rel="noreferrer">
            Chemogenetic suppression of GnRH neurons during pubertal development can alter adult
            GnRH neuron firing rate and reproductive parameters in female mice
          </a>
          <span className="cite">
            Dulka EA, DeFazio RA, Moenter SM. <em>eNeuro.</em> 2020;7(3):ENEURO.0223-20.2020. PMID
            32513661.
          </span>
        </li>
        <li>
          <a href="https://doi.org/10.1098/rsos.201040" target="_blank" rel="noreferrer">
            Firing patterns of gonadotropin-releasing hormone neurons are sculpted by their
            biologic state
          </a>{" "}
          — applies CLUSTER to firing rate rather than hormone concentration, and usefully reports
          a parameter-sensitivity check: cluster sizes of 1–5, t-scores of 1–3, and local versus
          global error models did not change the conclusions.
          <span className="cite">
            Penix J, DeFazio RA, Dulka EA, Schnell S, Moenter SM. <em>R Soc Open Sci.</em>{" "}
            2020;7(8):201040. PMID 32968535.
          </span>
        </li>
      </ul>
      <p>
        The serial tail-tip blood sampling protocol and ultrasensitive LH ELISA that make
        pulse-resolved sampling in mice practical come from a different group — Steyn and
        colleagues, with Herbison and Chen — and are worth citing separately if you use them:{" "}
        <a href="https://doi.org/10.1210/en.2013-1502" target="_blank" rel="noreferrer">
          Development of a methodology for and assessment of pulsatile luteinizing hormone
          secretion in juvenile and adult male mice
        </a>
        <span className="cite">
          Steyn FJ, Wan Y, Clarkson J, Veldhuis JD, Herbison AE, Chen C. <em>Endocrinology.</em>{" "}
          2013 Dec;154(12):4939–45. PMID 24092638.
        </span>
      </p>

      <h2>Other tools, and when to prefer them</h2>
      <p>
        CLUSTER is one option among several, and for many questions it is not the best one. If you
        need secretion rates, pulse mass, or half-life, you want deconvolution. If you need
        uncertainty on the number of pulses rather than a single answer, you want a Bayesian
        method. The tools below are real, findable, and — unless noted — still usable today.
      </p>

      <h3>Actively usable</h3>
      <ul>
        <li>
          <a href="https://pulsar.otago.ac.nz" target="_blank" rel="noreferrer">
            PULSAR Otago
          </a>{" "}
          — a modern R/Shiny reimplementation of the classic PULSAR detector, usable as a hosted
          web app or from{" "}
          <a href="https://github.com/phadenz/PulsarOtago" target="_blank" rel="noreferrer">
            source
          </a>
          . The closest thing to a directly comparable alternative to this app, and the most
          practical starting point if you want a second opinion on your data.
          <span className="cite">
            Porteous R, Haden P, Hackwell ECR, et al.{" "}
            <a href="https://doi.org/10.1210/endocr/bqab165" target="_blank" rel="noreferrer">
              <em>Endocrinology.</em> 2021;162(11):bqab165
            </a>
            . PMID 34383026.
          </span>
        </li>
        <li>
          <a href="https://doi.org/10.1371/journal.pcbi.1011928" target="_blank" rel="noreferrer">
            hormoneBayes
          </a>{" "}
          — the most current approach in this space. Instead of counting discrete pulses, it fits a
          generative model of latent hypothalamic drive with sequential Monte Carlo and returns
          posterior uncertainty on inter-pulse interval, secretion, and clearance. C++ with a
          Python interface; the download link is given in the paper&apos;s data-availability
          statement.
          <span className="cite">
            Voliotis M, Abbara A, Prague JK, Veldhuis JD, Dhillo WS, Tsaneva-Atanasova K.{" "}
            <em>PLoS Comput Biol.</em> 2024;20(2):e1011928. PMID 38422116.
          </span>
        </li>
        <li>
          <a href="https://github.com/BayesPulse/pulsatile" target="_blank" rel="noreferrer">
            pulsatile (R)
          </a>{" "}
          — Bayesian deconvolution with birth–death MCMC, so pulse number is inferred jointly with
          everything else. Honest caveat: it is research code, not on CRAN, and unmaintained since
          2019 — installable from source, but expect to work for it.
          <span className="cite">
            Method: Johnson TD.{" "}
            <a href="https://doi.org/10.1111/1541-0420.00075" target="_blank" rel="noreferrer">
              <em>Biometrics.</em> 2003;59(3):650–60
            </a>
            . PMID 14601766.
          </span>
        </li>
        <li>
          <a href="https://atoms.scilab.org/toolboxes/Dynpeak" target="_blank" rel="noreferrer">
            DynPeak (Scilab)
          </a>{" "}
          — a shape- and duration-aware detector aimed at inter-pulse-interval estimation, with
          built-in outlier diagnosis.
          <span className="cite">
            Vidal A, Zhang Q, Médigue C, Fabre S, Clément F.{" "}
            <a href="https://doi.org/10.1371/journal.pone.0039001" target="_blank" rel="noreferrer">
              <em>PLoS ONE.</em> 2012;7(7):e39001
            </a>
            . PMID 22802933.
          </span>
        </li>
        <li>
          <a
            href="https://github.com/HRunvik/Impulsive-Time-Series-Modeling"
            target="_blank"
            rel="noreferrer"
          >
            Impulsive time-series modeling
          </a>{" "}
          — a control-theory take that models bursts as impulses driving a linear system and
          derives the fit-versus-sparsity trade-off analytically, so there is no threshold to tune
          by hand.
          <span className="cite">
            Runvik H, Medvedev A.{" "}
            <a href="https://doi.org/10.3389/fendo.2022.957993" target="_blank" rel="noreferrer">
              <em>Front Endocrinol.</em> 2022;13:957993
            </a>
            . PMID 36387902.
          </span>
        </li>
      </ul>

      <h3>Methods worth knowing, without current software</h3>
      <ul>
        <li>
          <a href="https://doi.org/10.1016/j.ab.2008.07.001" target="_blank" rel="noreferrer">
            AutoDecon
          </a>{" "}
          — the direct successor to CLUSTER from the same group: fully automated, with statistical
          testing of each candidate burst and simultaneous fitting of half-life and basal
          secretion. It is the standard against which CLUSTER&apos;s sensitivity is usually quoted.
          The original distribution site is gone and we could not find a maintained mirror, so
          treat it as a reference method rather than a tool you can run.
          <span className="cite">
            Johnson ML, Pipes L, Veldhuis PP, Farhy LS, Boyd DG, Evans WS. <em>Anal Biochem.</em>{" "}
            2008;381(1):8–17. PMID 18639514.
          </span>
        </li>
        <li>
          <a href="https://doi.org/10.1073/pnas.84.21.7686" target="_blank" rel="noreferrer">
            Multi-parameter deconvolution
          </a>{" "}
          — the original deconvolution paper, which reframed the problem as secretion convolved
          with an elimination kernel rather than bumps in a concentration curve.
          <span className="cite">
            Veldhuis JD, Carlson ML, Johnson ML. <em>PNAS.</em> 1987;84(21):7686–90.
          </span>
        </li>
        <li>
          <a href="https://doi.org/10.1152/ajpendo.1982.243.4.E310" target="_blank" rel="noreferrer">
            PULSAR
          </a>{" "}
          (Merriam &amp; Wachter, <em>Am J Physiol.</em> 1982;243(4):E310–8) and{" "}
          <a href="https://doi.org/10.1016/0010-4809(86)90014-5" target="_blank" rel="noreferrer">
            DETECT
          </a>{" "}
          (Oerter, Guardabasso &amp; Rodbard, <em>Comput Biomed Res.</em> 1986;19(2):170–91) —
          CLUSTER&apos;s contemporaries, useful for understanding why the field converged on
          error-scaled thresholds.
        </li>
      </ul>

      <h3>Choosing between them</h3>
      <ul>
        <li>
          <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC4535452/" target="_blank" rel="noreferrer">
            A comparison of methods for analyzing time series of pulsatile hormone data
          </a>{" "}
          — the most useful head-to-head. Its warning generalizes: ignoring a changing (e.g.
          circadian) baseline biases every parameter, whichever method you use.
          <span className="cite">
            Carlson NE, Horton KW, Grunwald GK. <em>Stat Med.</em> 2013;32(26):4624–38. PMID
            23787487.
          </span>
        </li>
        <li>
          <a href="https://doi.org/10.1210/er.2008-0005" target="_blank" rel="noreferrer">
            Motivations and methods for analyzing pulsatile hormone secretion
          </a>{" "}
          — the standard review of what pulse analysis is actually trying to measure.
          <span className="cite">
            Veldhuis JD, Keenan DM, Pincus SM. <em>Endocr Rev.</em> 2008;29(7):823–64. PMID
            18940916.
          </span>
        </li>
      </ul>
      <p>
        One gap worth naming: despite the obvious appeal, there is no modern deep-learning pulse
        detector for serial hormone assays in routine use. It was tried in the 1990s — Prank and
        colleagues located growth-hormone secretory bursts with adaptive mixtures of local experts
        (<em>Hum Reprod Update</em> 1997;3(3):215–34), and a 1994 abstract trained a
        back-propagation network on fifteen series against expert-marked pulses (<em>Pediatr Res</em>{" "}
        35:A82) — but neither entered use, and the second illustrates the central difficulty: with
        no ground truth to learn from, it could only imitate an expert, inheriting whatever that
        expert got wrong. Adjacent machine-learning work exists on hormone trajectory prediction
        and cycle-phase classification. Nothing since identifies pulses in a concentration time
        series with a learned model the way the tools above do.
      </p>

      <h2>This implementation</h2>
      <p>
        The source and test suite are on GitHub under an MIT license. Neither reference
        implementation is redistributed with it, for different reasons: Johnson&apos;s Fortran is
        under a license that forbids passing it on, and the Igor Pro Cluster package is the
        laboratory&apos;s own code, which this app is intended to succeed. If you find a case where
        no_peak disagrees with Igor or the original Fortran, that is a bug worth reporting: please
        get in touch with the data and parameters.
      </p>

      <h2>Get in touch</h2>
      <p>
        Questions about the algorithm, bug reports, requests for a dataset or feature, and
        corrections to anything on this page are all welcome.
      </p>
      <ContactForm />

      <p style={{ marginTop: 32 }}>
        <button onClick={onBack}>← Back to the app</button>
      </p>
    </div>
  );
}
