// Sample datasets bundled with the app.
//
// These are SIMULATED, not experimental. Real lab recordings are not
// distributed with this app or its repository; the files here are generated by
// tools/make_synthetic.py from a seeded PRNG and match the real data only in
// character — sampling rate, baseline level, pulse amplitude range, assay CV.
// They are labelled as simulated everywhere they appear so nobody can mistake
// a demo figure for data.

import { parseSeries, type ParsedSeries } from "./core/csv";
import { demoSeries } from "./demo";

import gnrhCsv from "../data/synthetic/sim_gnrh.csv?raw";
import lhCsv from "../data/synthetic/sim_lh.csv?raw";
import lhLongCsv from "../data/synthetic/sim_lh_long.csv?raw";
import valuesOnlyCsv from "../data/synthetic/sim_values_only.csv?raw";
import flatCsv from "../data/synthetic/sim_flat_control.csv?raw";

export interface Sample {
  key: string;
  /** Group heading in the picker. */
  group: string;
  /** Short human label; the point count is appended at render time. */
  label: string;
  load: () => ParsedSeries;
}

const csv = (text: string) => () => parseSeries(text);

export const SAMPLES: Sample[] = [
  {
    key: "sim_gnrh",
    group: "Simulated, with error column",
    label: "GnRH-like (fast sampling, sharp pulses)",
    load: csv(gnrhCsv),
  },
  {
    key: "sim_lh",
    group: "Simulated, with error column",
    label: "LH-like (baseline plus modest pulses)",
    load: csv(lhCsv),
  },
  {
    key: "sim_lh_long",
    group: "Simulated, with error column",
    label: "LH-like, long run (10-min sampling)",
    load: csv(lhLongCsv),
  },
  {
    key: "sim_flat_control",
    group: "Simulated, with error column",
    label: "Flat control (no pulses — checks false positives)",
    load: csv(flatCsv),
  },
  {
    key: "sim_values_only",
    group: "Simulated, no time column",
    label: "Values only (uses the sampling interval)",
    load: csv(valuesOnlyCsv),
  },
  {
    key: "demo",
    group: "Simulated, no error column",
    label: "Demo (seeded LH-like series)",
    load: () => {
      const { times, values } = demoSeries();
      return { times, values, error: null, labels: null };
    },
  },
];

export const SAMPLE_GROUPS = [...new Set(SAMPLES.map((s) => s.group))];

/** Point counts for the picker labels; a file that fails to parse is skipped. */
export const sampleCounts: Record<string, number> = Object.fromEntries(
  SAMPLES.flatMap((s) => {
    try {
      return [[s.key, s.load().values.length]];
    } catch {
      return [];
    }
  }),
);
