// Sample datasets bundled with the app.
//
// These are SIMULATED, not experimental. Real lab recordings are not
// distributed with this app or its repository. They are generated by
// tools/make_synthetic.py from a seeded PRNG and match no animal and no
// experiment — but their scales (sampling interval, baseline, pulse amplitude,
// pulse frequency, assay CV) are taken from the published literature rather
// than invented, and each carries its own sampling interval and time unit so a
// demo figure is never plotted on a fictitious axis.
//
// See data/synthetic/README.md for the sources and the standard any test data
// added here has to meet.

import { parseSeries, type ParsedSeries } from "./core/csv";
import type { TimeUnit } from "./core/timeUnits";
import { demoSeries } from "./demo";

import gnrhCsv from "../data/synthetic/sim_gnrh_portal.csv?raw";
import gnrhFastCsv from "../data/synthetic/sim_gnrh_highfreq.csv?raw";
import lhCsv from "../data/synthetic/sim_lh.csv?raw";
import lhLongCsv from "../data/synthetic/sim_lh_long.csv?raw";
import valuesOnlyCsv from "../data/synthetic/sim_values_only.csv?raw";
import flatCsv from "../data/synthetic/sim_flat_control.csv?raw";

export interface Sample {
  key: string;
  /** Group heading in the picker. */
  group: string;
  /** Short human label; the point count is appended at render time. */
  label: string;
  /** What it is meant to resemble, and on what evidence. */
  note: string;
  /** Units of the sample times. */
  timeUnit: TimeUnit;
  /** Sampling interval, for the files that carry no time column. */
  deltaT: number;
  /** Units of the measured values, for the y-axis label. */
  valueLabel: string;
  load: () => ParsedSeries;
}

const csv = (text: string) => () => parseSeries(text);

const PORTAL = "Simulated portal GnRH";
const PERIPHERAL = "Simulated peripheral LH";

export const SAMPLES: Sample[] = [
  {
    key: "sim_gnrh_portal",
    group: PORTAL,
    label: "10-min fractions, ~50-min pulse interval",
    note:
      "Hypophyseal-portal GnRH as collected in 10-min fractions over 16 h. Secretory bursts are " +
      "square waves of about 5.5 min on a 0.3 pg/min baseline, so a pulse occupies one or two " +
      "fractions and returns abruptly — GnRH is cleared far faster than a collection window, and " +
      "has no decay tail at this resolution.",
    timeUnit: "min",
    deltaT: 10,
    valueLabel: "GnRH (pg/min)",
    load: csv(gnrhCsv),
  },
  {
    key: "sim_gnrh_highfreq",
    group: PORTAL,
    label: "6-min fractions, high pulse frequency (hard case)",
    note:
      "The same secretion model driven at roughly a 20-min pulse interval and sampled every 6 min, " +
      "leaving only about three samples per cycle. Deliberately hard: the peak and nadir windows " +
      "start to overlap neighbouring pulses, so it is a good test of how far the window settings " +
      "can be pushed.",
    timeUnit: "min",
    deltaT: 6,
    valueLabel: "GnRH (pg/min)",
    load: csv(gnrhFastCsv),
  },
  {
    key: "sim_lh",
    group: PERIPHERAL,
    label: "10-min sampling over 12 h",
    note:
      "Jugular LH: a substantial baseline with modest pulses that decay over several samples. " +
      "Unlike GnRH, exponential clearance is right here — LH's half-life is long compared with " +
      "the sampling interval.",
    timeUnit: "min",
    deltaT: 10,
    valueLabel: "LH (ng/ml)",
    load: csv(lhCsv),
  },
  {
    key: "sim_lh_long",
    group: PERIPHERAL,
    label: "24-h run, lower pulse frequency",
    note: "A full-day LH time course at 10-min sampling, with pulses roughly every three hours.",
    timeUnit: "min",
    deltaT: 10,
    valueLabel: "LH (ng/ml)",
    load: csv(lhLongCsv),
  },
  {
    key: "sim_flat_control",
    group: PERIPHERAL,
    label: "Flat control, no pulses (checks false positives)",
    note:
      "Assay noise around a constant baseline and nothing else. Every pulse reported here is a " +
      "false positive, which makes it the quickest way to see what a settings change costs.",
    timeUnit: "min",
    deltaT: 10,
    valueLabel: "LH (ng/ml)",
    load: csv(flatCsv),
  },
  {
    key: "sim_values_only",
    group: "Simulated, other shapes",
    label: "Values only — no time column",
    note:
      "The same LH model written without a time column, to show what happens when the sampling " +
      "interval has to be supplied by hand. It was generated at 10-min sampling.",
    timeUnit: "min",
    deltaT: 10,
    valueLabel: "LH (ng/ml)",
    load: csv(valuesOnlyCsv),
  },
  {
    key: "demo",
    group: "Simulated, other shapes",
    label: "Demo — no error column",
    note:
      "A seeded LH-like series with no per-sample error, so the error model has to be estimated " +
      "from the data itself.",
    timeUnit: "min",
    deltaT: 10,
    valueLabel: "LH (ng/ml)",
    load: () => {
      const { times, values } = demoSeries();
      return { times, values, error: null, labels: null };
    },
  },
];

export const SAMPLE_GROUPS = [...new Set(SAMPLES.map((s) => s.group))];

export const sampleByKey = (key: string) => SAMPLES.find((s) => s.key === key);

/** Point counts for the picker labels; a file that fails to parse is skipped. */
export const sampleCounts: Record<string, number> = Object.fromEntries(
  SAMPLES.flatMap((s) => {
    try {
      return [[s.key, s.load().values.length]];
    } catch {
      return [];
    }
  }),
);
